export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const EVENTS_ROUTE = '/'
export const EVENT_ROUTE = '/event'
export const CONTENT_ROUTE = '/content'

export const ADMIN_ROUTE = '/admin'
export const ADMIN_EVENTS = '/admin/events'
export const ADMIN_CONTENT = '/admin/content'
export const ADMIN_CATEGORIES = '/admin/category'