// Создание категории 
POST http://localhost:3333/api/v1/category/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGFzc3dvcmQiOiIkMmIkMTAkQ3NuYWk4REpqN2guSmtCeU03OWNxLjNkRi5xYzZZOE9xWVFwSlFEVFJyNGdUd2J3ME42cG0iLCJpYXQiOjE2MzQyODg2NTh9.k5sH6Ifj7fSFOtTi0yYUnFwSM59N8CpRv1qedZGzwWs

// параметры
{
  "args": {
    "data": {
      "title": "first",
      "image": 1
    }
  }
}