version: '3.8'
services:
  db:
    image: mariadb:10-focal
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boring_db
      MYSQL_USER: arch
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3333:3000'
    container_name: api
    depends_on:
      - db
    volumes:
      - ./cloud:/home/app/cloud
    command: npm run start
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file